version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-mall
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root #设置root帐号密码
    ports:
      - 3306:3306
    volumes:
      - /home/mall-apps/dev-data/mysql/data/db:/var/lib/mysql #数据文件挂载
      - /home/mall-apps/dev-data/mysql/data/conf:/etc/mysql/conf.d #配置文件挂载
      - /home/mall-apps/dev-data/mysql/log:/var/log/mysql #日志文件挂载
  redis:
    image: redis:7
    container_name: redis-mall
    command: redis-server --appendonly yes
    volumes:
      - /home/mall-apps/dev-data/redis/data:/data #数据文件挂载
    ports:
      - 6379:6379
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq-mall
    volumes:
      - /home/mall-apps/dev-data/rabbitmq/data:/var/lib/rabbitmq #数据文件挂载
      - /home/mall-apps/dev-data/rabbitmq/log:/var/log/rabbitmq #日志文件挂载
    ports:
      - 5672:5672
      - 15672:15672
  elasticsearch:
    image: elasticsearch:7.17.3
    container_name: elasticsearch-mall
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m" #设置使用jvm内存大小
    volumes:
      - /home/mall-apps/dev-data/elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - /home/mall-apps/dev-data/elasticsearch/data:/usr/share/elasticsearch/data #数据文件挂载
    ports:
      - 9200:9200
      - 9300:9300
  logstash:
    image: logstash:7.17.3
    container_name: logstash-mall
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /home/mall-apps/dev-data/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf #挂载logstash的配置文件
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    ports:
      - 4560:4560
      - 4561:4561
      - 4562:4562
      - 4563:4563
  kibana:
    image: kibana:7.17.3
    container_name: kibana-mall
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "elasticsearch.hosts=http://es:9200" #设置访问elasticsearch的地址
    ports:
      - 5601:5601
  mongo:
    image: mongo:4
    container_name: mongo-mall
    volumes:
      - /home/mall-apps/dev-data/mongo/db:/data/db #数据文件挂载
    ports:
      - 27017:27017
  minio:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    container_name: minio-mall
    command: server /data
    restart: always
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123456
    volumes:
      #- /home/mall-apps/dev-data/mongo/db:/data/db #数据文件挂载
      - /home/mall-apps/dev-data/minio/data:/data
      - /home/mall-apps/dev-data/minio/config:/root/.minio
    ports:
      - 19000:9000