apiVersion: batch/v1
kind: Job
metadata:
  name: job1
  namespace: immu
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  template:
    spec:
      containers:
      - name: erer
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(1090)"]
      restartPolicy: Never
  backoffLimit: 4