apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: immu
  name: r2
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["apps"]
  verbs: ["get", "watch", "list"]