apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-search
  namespace: mall
  labels:
    app: mall-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall-search
  template:
    metadata:
      labels:
        app: mall-search
    spec:
      containers:
        - name: mall-search
          image: yt9999/mall-all-in-one:1.0
          imagePullPolicy: IfNotPresent
          #<entryPoint>["java", "-jar", "-Dspring.profiles.active=prod","/${project.build.finalName}.jar"]-->
          command: ["java", "-jar", "-Dspring.profiles.active=prod", "/home/mall-search-1.0-SNAPSHOT.jar"]
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: mall-search
  namespace: mall
spec:
  selector:
    app: mall-search
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mall-search
  namespace: mall
spec:
  rules:
    - host: "mall-search.mall-k8s.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: mall-search
                port:
                  number: 8081